# Generated by Django 4.0.3 on 2023-08-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationvo',
            options={'ordering': ('closet_name', 'section_number', 'shelf_number')},
        ),
        migrations.RenameField(
            model_name='hat',
            old_name='picUrl',
            new_name='picture_uyrl',
        ),
        migrations.AddField(
            model_name='locationvo',
            name='section_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='locationvo',
            name='shelf_number',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
