# Generated by Django 4.0.3 on 2023-08-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0002_alter_locationvo_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hat',
            old_name='picture_uyrl',
            new_name='picture_url',
        ),
    ]
