# Generated by Django 4.0.3 on 2023-08-30 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='name',
        ),
        migrations.AddField(
            model_name='binvo',
            name='number',
            field=models.PositiveSmallIntegerField(default=None),
        ),
    ]
