# Generated by Django 4.0.3 on 2023-08-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0002_remove_binvo_name_binvo_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='binvo',
            name='bin_size',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='binvo',
            name='closet_name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
